QubesOS/qubes-gui-agent-linux

xf86-input-mfndev/src/qubes.c

I unfortunately missed that QubesWorkProc() is not intended to be called from the input thread since it's not thread safe (unlike the quite similar Timer-API).
While I did not experienced any problems myself this hopefully fixes the problems reported with my fix for QubesOS/qubes-issues#2617 (PR #12).

xf86-input-mfndev: don't use QueueWorkProc() in input thread

---

xf86-input-mfndev/src/qubes.c

This PR contains two fixes to the Xorg mfndev "driver".
203c38b:
Newer Xservers with an input thread wake up the main loop after handling a request and therefore ensure that the BlockHanlder is called. Unthreaded Xservers don't do this, so do the request handling directly like before. Should fix QubesOS/qubes-issues#2772
99fce91:
When killing Xorg the loop in QubesReadInput() can run endless since xf86WaitForInput() will return > 0. For some reasons this sometimes causes very slow shutdowns of VMs with the threading changes but not without them (probably some timing thing).
I tested that:
- I can't anymore observe the problems from QubesOS/qubes-issues#2772 with a Debian 8 template (Xorg without input thread).
- QubesOS/qubes-issues#2617 doesn't reappear with a Debian 9 template (Xorg …

fix unthreaded input and hang on shutdown

---

pulse/module-vchan-sink.c

The commit included in this pull request adds "port"s to the Qubes OS vchan pulseaudio module, so that recent versions of Firefox can detect a microphone.
Without this commit, a microphone cannot be detected by Firefox 48 and 49 on an AppVM even if the microphone is attached to the AppVM in question. Apparently, recent versions of Firefox inspect the pulseaudio "port"s to determine whether a microphone is plugged in.
Please see the commit message for more details.
Thank you!

pulseaudio: Create a card, a profile and ports

---

rpm_spec/gui-agent.spec

Replace python-xpyb by python-xcffib

Replace python-xpyb by python-xcffib

---

rpm_spec/gui-vm.spec

Replace python-xpyb by python-xcffib.

Release3.2

---

appvm-scripts/usrbin/qubes-run-xorg.sh
debian/control

(Cherry picked commit 378a9cc57c3c788c97e75253b7e4f81440e50fe2)

 debian: adjust Xorg path for Debian stretch

---

appvm-scripts/usrbin/qubes-run-xorg.sh

Using the default_user available in qubesdb to start X to fix issue https://github.com/QubesOS/qubes-issues/issues/2372

Using the default_user available in qubesdb to start X

---

rpm_spec/gui-agent.spec.in

spec: fix missing abi version requirement

---

gui-agent/vmside.c
gui-common/error.c

Fix GCC9 warning about size in strncpy

---

Makefile
rpm_spec/gui-agent.spec.in

Fixes QubesOS/qubes-issues#5060

Init script qubes-gui-agent is not needed anymore

---

pulse/module-vchan-sink.c

this allows configuring audio vms (usb, bt) and connecting them as sinks/sources to dom0 pulseaudio.
`dom0$ pactl load-module module-vchan-sink domid=353 sink_desc=\'Qubes sink sys-bt\' source_desc=\'Qubes source sys-bt\'`
`sys-bt$ pacat-simple-vchan 0 dom0`
now you have a sink+source in dom0 mixer/pavucontrol, and dom0 in sys-bt mixer and can configure what goes where as needed.
building it is a mess at the moment since both parts are currently in very dom0/appvm specific qubes-gui packages.
only sane way i see is moving them into their own qubes-pulse component together and building it for both dom0 and distvms.
with that in place, adding a device class audio and a qvm-audio frontend to set up and tear down additional any-to-any audio connections is mostly trivial.

add modargs for target domid and sink/source descr strings

---

rpm_spec/gui-agent.spec.in

QubesOS/qubes-issues#5289
To be merged with https://github.com/QubesOS/qubes-gui-agent-linux/pull/68 https://github.com/QubesOS/qubes-gui-agent-linux/pull/69

spec: handle newer pulseaudio for Fedora 31+

---

archlinux/PKGBUILD

archlinux: qubes-vm-gui: update PKGBUILD

---

pulse/Makefile
pulse/module-vchan-sink.c

Conditionally use qubesdb dependency in vchan-sink module

---

gui-agent/vmside.c

vmside: use XKillClient() if WM_DELETE_WINDOW is unsupported

---

xf86-video-dummy/src/dummy_driver.c

xf86-video-dummy: improve error message on xengntshr_open fail

---

patches.debian/01_setXDG_DIR.patch

Perform a quilt refresh to resolve QubesOS/qubes-issues#6187 as patch doesn't allow fuzz.

[ubuntu] Perform quilt refresh for ubuntu-only patch

---

Makefile

Closes QubesOS/qubes-issues#6306

Fix pulseaudio in Ubuntu templates

---

rpm_spec/gui-agent.spec.in

Related https://fedoraproject.org/wiki/Changes/XorgUtilityDeaggregation

spec: ensure R for few x11 tools

---

gui-agent/vmside.c

The GUI daemon won’t accept subwindows for much longer.  Thankfully, the only ways that a MSG_CREATE with a non-root parent can be sent are either a managed window being reparented, or a window being created with an embedder window as parent.  Both are easy enough to check for.
This also fixes some minor problems: the X Intrinsics Toolkit header was unnecessarily #include’d, and an Xlib internal header was included without a very good reason.
Marking as draft because it has not been tested yet.

Ensure that no subwindows are created

---

appvm-scripts/usrbin/qubes-session

This could be offensive to some and it serves no purpose.

Remove hanging person image

---

appvm-scripts/etc/qubes/post-install.d/20-qubes-guivm-gui-agent.sh
gui-agent/vmside.c

Add functionality that automatically wipes the clipboard after a minute from the last vm paste.
https://github.com/QubesOS/qubes-issues/issues/3415

Add automatic clipboard wipe

---

.qubesbuilder
Makefile
Makefile.builder
appvm-scripts/etc/pam.d/qubes-gui-agent
appvm-scripts/usr/lib/qubes/qubes-gui-agent-pre.sh
appvm-scripts/usr/lib/qubes/qubes-xorg-wrapper
appvm-scripts/usrbin/qubes-run-xorg
appvm-scripts/usrbin/qubes-session
debian/qubes-gui-agent.install
rpm_spec/gui-agent-vm.spec.in
rpm_spec/gui-agent.spec.in
selinux/qubes-gui-agent.fc
selinux/qubes-gui-agent.te

This allows the GUI agent to run with SELinux enforcing.  Part of QubesOS/qubes-issues#4239.

SELinux support

---

.qubesbuilder

QubesOS/qubes-issues#8160
FYI @fepitre

Fix setting pipewire-qubes as recommended under Ubuntu jammy

---

.qubesbuilder
debian/control

https://github.com/QubesOS/qubes-issues/issues/8160

pipewire-qubes: add pipewire-pulse dependency

---

debian/control

Fix https://github.com/QubesOS/qubes-issues/issues/8189

Add libpam-systemd as dependency

---

rpm_spec/gui-agent.spec.in
xf86-input-mfndev/autogen.sh

https://github.com/QubesOS/qubes-issues/issues/8499

Update for Fedora 39

---

Makefile
debian/qubes-gui-vnc.install
pipewire/Makefile
rpm_spec/gui-agent.spec.in

Packaging changes for openSUSE

---

pipewire/qubes-pw-module.c

No functional change intended.

Clarify input vs output streams

---

archlinux/PKGBUILD.in

Fixes QubesOS/qubes-issues#9660

Fix pulseaudio/pipewire dependencies on Arch

---

include/xdriver-shm-cmd.h

Hello, 
little PR to fix an obsolete link in a header file
Best Regards,

Updated broken gui docs link

---

gui-agent/vmside.c
include/unix-addr.h
xf86-input-mfndev/src/qubes.c
xf86-video-dummy/src/dummy_driver.c

See individual commit messages.
Started with fixing https://github.com/QubesOS/qubes-gui-agent-linux/pull/236#discussion_r2160022793 added a few other smaller cleanups while at it.

Various cleanups
