QubesOS/qubes-gui-agent-linux

Makefile

After trying various alternatives, it seems to me that the cleanest solution here is just to do nothing for Xenial, and to use the Ubuntu Trolltech.conf without override. If there are display issues, (and I haven't seen any in testing), it's just a standard Trolltech problem, easily resolvable by user.

Exclude Trolltech.conf in Xenial build

---

Makefile.builder
debian-quilt
debian/rules
debian/source/format
patches.debian/01_setXDG_DIR.patch
series-debian-vm.conf

This should be final part of xenial build, fixing QubesOS/qubes-issues#2430
Package format has been changed to use quilt. The debian changelog will need to be updated as part of final package build.

Provide XDG_DATA_DIRS in Xenial. Also update deb package to 3.0 quilt)

---

Makefile
patches.debian/01_setXDG_DIR.patch

Tidy Debian patch for XDG_DATA_DIRS
Stop Ubuntu builds from overwriting Trolltech.conf
One of fixes for QubesOS/qubes-issues#2608

Fix build for Trusty

---

xf86-input-mfndev/src/qubes.c
xf86-input-mfndev/src/qubes.h

Newer Xsevers have a separate thread for input processing. Therefore we should no longer directly access window objects because they can change while we are running. To fix this dump the window memory MFNs in the main thread via QueueWorkProc().
Most likely fixes QubesOS/qubes-issues#2617.
Since the code was a bit messy formated (mix between tabs/spaces and ts=4/ts=8, trailing whitespace, old out-commented code), I first cleaned it up. If you don't like it I can rebase it.

xf86-input-mfndev: don't access windows in input thread

---

Makefile.builder

4.0 template builds use `<package>.install` files with dh_install.
The differences between Debian and Ubuntu packages also need to be
represented in these files.
The XDG changes for Xenial are also beneficial in Trusty.

Fix Ubuntu template builds; apply XDG changes for all Ubuntu templates.

---

archlinux/PKGBUILD

This adds a dependency as detected to be missing in bug report #3185

Make compile on archlinux

---

window-icon-updater/icon-sender

xpyb in Fedora 26 (and probably others) have problems with parsing X
events, like this:
Traceback (most recent call last):
File "/usr/lib/qubes/icon-sender", line 155, in <module>
retriever.watch_and_send_icons()
File "/usr/lib/qubes/icon-sender", line 136, in watch_and_send_icons
[xproto.EventMask.SubstructureNotify])
File "/usr/lib64/python2.7/site-packages/xcb/xproto.py", line 1400, in ChangeWindowAttributesChecked
for elt in xcb.Iterator(value_list, 15, 'value_list', False):
xcb.Exception: Too few items in 'value_list' list (expect 15).
QubesOS/qubes-issues#1495

icon-sender: prefer xcffib module over xpyb

---

Makefile
rpm_spec/gui-agent.spec

I put the XFCE script in a separate make target. Notably because of Archlinux. If I understand correctly the packaging of Archlinux, each package is made with specific make target. It will allow to do the packaging for the XFCE script with simply make install-xfce. For Fedora and Debian, we could think in the future for a make target like install-flavors. What do you think?

desktop flavor: specific XFCE make target

---

appvm-scripts/etc/X11/xorg-qubes.conf.template
appvm-scripts/usrbin/qubes-run-xorg.sh

Restore dynamic video ram calculation. But to allow dynamic display connection, add some extra ram - enough for one more Full HD display. If more is needed, we can adjust it later (make it configurable somewhere), but for now attaching more displays will require VM restart. Previous hardcoded value was enough for two 4K displays, regardless of when they were attached.
Fixes QubesOS/qubes-issues#3174
Fixes QubesOS/qubes-issues#3634

Dynamic video ram

---

rpm_spec/gui-vm.spec

(cherry picked from commit 84b10aa7ca200173ba2974a5a3fd96c1709de760)

spec.in: python-xcffib -> python2-xcffib for Fedora >=28

---

pulse/module-vchan-sink.c

In pulse/module-vchan-sink.c unnessecary pulseaudio messages are
given. These are used for "debugging weird cases we haven't seen
in years". This creates noise in logs.
Fixes https://github.com/QubesOS/qubes-issues/issues/3933.
(sorry in the commit message it just has #3993 not the link to qubes-issues)

Remove unnessecary pulseaudio message

---

archlinux/PKGBUILD

Untested, but corresponds to https://github.com/QubesOS/qubes-gui-agent-linux/commit/a2db14cb91622c64d1172124b880802f6b8ecb94 and https://github.com/QubesOS/qubes-gui-agent-linux/commit/4ae178c2bafb3d02ef2f5d44fdaf19d29c0c7501

Bump Arch pulseaudio to 12.2 too

---

debian/control
debian/rules

Since the pulseaudio-qubes package ships a pulseaudio module linked for
specific version, it needs to specify that in dependencies - otherwise
updating one but not the other will result in broken audio.
Since pulseaudio package does not provide substvars itself (in fact
pulseaudio modules API is not meant for external packages), generate
it in debian/control.
The version in MAJOR.MINOR form is enough (no need to compare
debian_version), but since dependency syntax doesn't support partial
matches, add >= MAJOR.MINOR and << MAJOR.MINOR.1 entries.
The intention is to detect at installation time potential breakage,
especially on pulseaudio update.
Fixes QubesOS/qubes-issues#3532

debian: bind to specific pulseaudio version

---

gui-agent/vmside.c

For in-vm screenshots (including screen sharing etc) to work, window
composition buffers needs to be rendered back to root window. Using
"automatic" composition mode does that.
Fixes QubesOS/qubes-issues#4351

gui-agent: switch to automatic composition mode, fix in-vm screenshots

---

archlinux/PKGBUILD

Fixes an invalid dependency on python3-xcffib (correct package name is
python-xcffib) which partially causes a build failure.

Fix python-xcffib dependency

---

archlinux/PKGBUILD

Bump xorg-server version from 1.20.1 to 1.20.3
As a side note, after this change and the other changes I submitted, I was able to build the Arch template successfully, although I have not tested yet. But once this is merged in, the Arch template should build smoothly.

Bump xorg-server version

---

appvm-scripts/usrbin/qubes-run-xorg

When starting X server inside qube, a fixed amount of RAM is allocated
to be used for video buffer. By default, it is enough for the current
desktop (at the time of qube start) and another 1920x1080 desktop, which
may be hotplugged in the future. That is not enough for 4K external
monitor, but we cannot preallocate 4K video buffer for everyone (about
24MiB additional memory per qube).
Now we allocate max(current desktop + overhead, min), where min and
overhead are configurable by qubesdb entries /qubes-gui-videoram-min and
/qubes-gui-videoram-overhead. Default behaviour remains unchanged.
QubesOS/qubes-core-admin#240

qubes-run-xorg: add configurable videoram overhead

---

Makefile
appvm-scripts/etc/pam.d/qubes-gui-agent
appvm-scripts/etc/pam.d/qubes-gui-agent.archlinux
appvm-scripts/etc/pam.d/qubes-gui-agent.debian
appvm-scripts/lib/udev/rules.d/70-master-of-seat.rules
appvm-scripts/qubes-gui-agent.service
appvm-scripts/usrbin/qubes-run-xorg
debian/control
debian/qubes-gui-agent.install
gui-agent/vmside.c
gui-common/Makefile
gui-common/qubes-gui-runuser.c
rpm_spec/gui-agent.spec.in

Most of the logind session registration is done by pam_systemd, but it
needs some extra data to properly register X11 session. Most of it can be
set using environment variables (XDG_SEAT, XDG_VTNR, XDG_SESSION_CLASS).
But at least DISPLAY cannot, it needs to be set with pam_set_item(3).
Unfortunately standard utilities like su or runuser don't do that, which
means we need our own wrapper for that.
Add qubes-gui-runuser, similar to runuser. The main difference is setting
everything needed for logind to recognize the session as graphical -
including PAM_XDISPLAY and use that instead of su. Note that the
qubes-run-xorg script is called as root, so the qubes-gui-runuser does not
need to have suid.
In addition to that, logind require seat to have at least one device with
master-of-seat tag, to …

Fix X11 session registration in logind

---

archlinux/PKGBUILD

This is the default and icon-sender code use python3 only
code anyway (such as sys.stdout.buffer)

archlinux: switch to using icon-sender with python3

---

gui-agent/vmside.c

This PR is linked to a matching PR to `qubes-gui-daemon`, see https://github.com/QubesOS/qubes-gui-daemon/pull/15/ for background.
It makes `send_clipboard_data` send the window id in the `window` field and the length of copied data in the `untrusted_len` field rather than sending the length in both.
It also touches on `handle_clipboard_data` to make it use the `untrusted_len` field for determining how much data to copy instead of using the `window` field. I also changed `len` in that function signature to take an `unsigned int` instead of a `signed int`, since that seemed more appropriate (please bear with me if that was incorrect).

CLIPBOARD_DATA: send window id, and ignore window id in incoming pastes

---

xf86-video-dummy/src/dummy_driver.c

Fixes QubesOS/qubes-issues#3253

video-dummy: fix off by one error in memory size check

---

appvm-scripts/qubes-gui-agent.service

Kernel in Debian has this set to "always" by default, which breaks u2mfn
module. Specifically, it tries to get address of an arbitrary memory
page mapped by X server, and it fails if it's merged into huge page.
u2mfn module is gone in the next Qubes release, so as a temporary
measure revert transparent hugepage to "madvise".
Do that only if it was set to "always". This will prevent overriding
other user choices.
QubesOS/qubes-issues#5212

Disable "transparent hugepage" kernel feature

---

Makefile
appvm-scripts/qubes-gui-agent.service
appvm-scripts/usr/lib/qubes/qubes-gui-agent-pre.sh
debian/qubes-gui-agent.install
pulse/start-pulseaudio-with-vchan
rpm_spec/gui-agent.spec.in

- gui-agent: put ExecPre in separate script
https://github.com/QubesOS/qubes-issues/issues/5662
https://github.com/QubesOS/qubes-issues/issues/833
https://github.com/QubesOS/qubes-issues/issues/1590

Allow GUI and AUDIO client to be ran before their corresonding servers

---

pulse/module-vchan-sink.c

Recreate vchan servers (libvchan_server_init()) on disconnection.
This fixes audio in the case of Xorg crash (see
QubesOS/qubes-issues#5273), and any kind of GUI restart.

pulseaudio: support reconnecting

---

window-icon-updater/icon-sender

Chromium uses 256x256 icons.
Needs fix to Python library on the receiving side:
QubesOS/qubes-linux-utils#54

Bump ICON_MAX_SIZE

---

archlinux/PKGBUILD

xorg-server have been updated to 1.20.8-1. 
Minor version change are unlikely to break compatibility.
So allowing all 1.20.X versions of xorg-server

Archlinux: more permissive with xorg-server update

---

window-icon-updater/icon-sender
window-icon-updater/qubes-icon-sender.desktop

This makes icon-sender handle GUI restart, same as qubes-gui and
audio. However, in this case we are not running raw vchan, but
Qubes RPC, so the procedure is more complicated: we start a
qrexec-client-vm subprocess, and restart it if it breaks.
Needs icon-receiver to be a service with wait-for-session
(QubesOS/qubes-gui-daemon#37), and fix for socket services in dom0
(QubesOS/qubes-core-qrexec#42).

icon-sender: reconnect on failure

---

archlinux/PKGBUILD

Following suggestion here: https://github.com/QubesOS/qubes-issues/issues/3908#issuecomment-563715196
Tracking issue: https://github.com/QubesOS/qubes-issues/issues/3908
I followed @marmarek proposal from last year (sorry for getting there only now) to update archlinux package based on ABI version instead of xorg-server version.
I'm not sure however if we need to check all the ABI versions for XEXTENSION, XINPUT and XVIDEO. I put all of them as dependency in the commit above.

archlinux: set dependencies on xorg server ABI version instead of server

---

appvm-scripts/qubes-gui-agent.service

On sys-gui-gpu we use lightdm for running X server, but we still need
guivm-gui-agent service
Part of: QubesOS/qubes-issues#2618

Do not run X server on sys-gui-gpu

---

Makefile
appvm-scripts/usrbin/qubes-run-xorg
appvm-scripts/usrbin/qubes-start-xephyr
debian/qubes-gui-agent.install
rpm_spec/gui-agent.spec.in

qubes-run-xorg will only start the "outer" Xorg instance. The
Xephyr session should be initiated using qrexec:
qvm-run -p --no-gui --service $GUIVM qubes.GuiVMSession
The '-p' ensures that the above command will wait for the session
to finish.

Extract Xephyr to a separate script

---

gui-agent/Makefile
gui-agent/vmside.c
gui-common/encoding.c
gui-common/error.c
include/encoding.h
include/error.h

libX11 claims to have Xutf8TextListToTextProperty for handling UTF-8
text, but it is just broken and winds up mangling the text instead.
Instead, use XStringListToTextProperty and validate UTF-8 validity
ourselves.
Fixes https://github.com/QubesOS/qubes-issues/issues/2845

Fix Unicode handling in Qubes clipboard

---

gui-agent/vmside.c

These changes implement the WM_STATE property on the X11 AppVM side - allowing applications to identify the toplevel windows of other applications that are running in the same VM.
This is necessary for "screen sharing" of individual windows in Firefox and possibly other, similar programs: https://github.com/QubesOS/qubes-issues/issues/5789

Implement WM_STATE in X11 GUI agent

---

appvm-scripts/qubes-gui-agent.service

Use After=systemd-user-sessions.service
This way, we can be sure to start user applications (including those
from /etc/xdg/autostart) only when they are supposed to be started.
Other system services may order themselves before
systemd-user-session.service (or any of related .target unit).

Start gui-agent only after systemd let in normal users

---

appvm-scripts/qubes-gui-agent.service

The former is deprecated in systemd.
Part of QubesOS/qubes-issues#6315.

Mass replace: ‘/var/run’ → ‘/run’

---

gui-agent/vmside.c

Don't write the terminating \0 past the buffer for WM_NAME >= 128 bytes.
Fixes QubesOS/qubes-issues#6444

(release4.0) vmside: fix strncat() buffer overflow in getwmname_tochar()

---

rpm_spec/gui-agent.spec.in

It solves deprecated and further removed xorg-x11-utils

spec: remove xorg-x11-utils and replace by dependencies

---

gui-agent/vmside.c

Best practice is to intern all X atoms at startup.

Remove the last XInternAtom call after startup

---

rpm_spec/gui-agent.spec.in

It used to be part of xorg-x11-server-utils
QubesOS/qubes-issues#6568

rpm: add xrandr dependency

---

appvm-scripts/usr/lib/qubes/qubes-keymap.sh

Setting only non-latin layout breaks hotkeys in various applications, so setup secondary 'us' to propagated from dom0.
Fixes https://github.com/QubesOS/qubes-issues/issues/5431
Fixes https://github.com/QubesOS/qubes-issues/issues/6690

Always keep latin keyboard layout

---

gui-agent/vmside.c

It was erroneously labeled as WM_DELETE_MESSAGE.
I was *not* able to test this, as building RPM packages failed (presumably due to a different bug).

Fix the name of WM_DELETE_WINDOW

---

appvm-scripts/usr/lib/qubes/qubes-keymap.sh

Hey, @marmarek and @jevank, I was super happy to see that https://github.com/QubesOS/qubes-issues/issues/6690 was fixed by https://github.com/QubesOS/qubes-gui-agent-linux/pull/139, and in a much simpler way than my original suggestion. Unfortunately, there is a bug in this fix when you have a non-standard `KEYMAP_VARIANT`. Right now, `qubes-keymap.sh` will execute this on my machine:
```sh
setxkbmap -display :0 -layout bg,us -variant phonetic -option grp:alt_shift_toggle
```
when the correct thing it should execute is this:
```
setxkbmap -display :0 -layout bg,us -variant phonetic, -option grp:alt_shift_toggle
```
Notice the comma after `phonetic` - it needs to be there when there are multiple layouts, even if the non-us layout is first, otherwise the `phonetic` variant to the `bg` …

Fix support for non-latin variants when we append the us layout

---

gui-agent/vmside.c

The message parameter should be the actual embedder window, not the
selection owner. This mismatch may confuse some applications that wait
to be re-parented into another window and fail to redraw itself until
then.
Fixes QubesOS/qubes-issues#6856

Fix XEMBED_EMBEDDED_NOTIFY parameters

---

archlinux/PKGBUILD

For more info, please see:
- https://github.com/QubesOS/qubes-issues/issues/7048#issuecomment-991975536
This change should be also backported to Qubes v4.0.

archlinux: add lsb-release into make dependencies

---

appvm-scripts/usrbin/qubes-session

The standard environment.d facility is currently not respected in Qubes OS 4.1.  This leads to inability to define environment variables when starting apps via qrexec¹.
This should be fixed.  Here is the fix — it is a fix that will not have any substantial performance impact (it runs *once*), and uses documented APIs to execute on the fix.  Furthermore, the fix enables packaged software to ship environment variables in `/usr/lib/environment.d` as per the standard, without which presumable at least some software will simply be broken.
¹ Technically there's `/etc/profile.d` but that's meant to be used for **shells**.  There is no guarantee that apps started via qrexec will inherit these variables, and that doesn't cover software packaging factory environment variable customization in …

Make qubes-session inherit the systemd user session variables.

---

get-latest-pulsecore.sh

It prevents calling split-gpg when it is configured in git config.

get-latest-pulsecore.sh: ensure to use gpg for git tag

---

pulse/start-pulseaudio-with-vchan

Disposable VMs are not implemented this way anymore.

Drop obsolete checks for disposable VM restore

---

pulse/module-vchan-sink.c

This ensures that pacat-simple-vchan will not need to block, and
therefore prevents overruns if it discards data rather than blocking.

Use larger vchan buffers

---

appvm-scripts/etc/X11/xorg-qubes.conf.template
debian/control
rpm_spec/gui-agent.spec.in
xf86-video-dummy/src/Makefile.am
xf86-video-dummy/src/dummy.h
xf86-video-dummy/src/dummy_driver.c

This enables native OpenGL support if render device available
(Intel mediated with GVT-g or passed through).
Based on https://patchwork.freedesktop.org/patch/143119/

dummyqbs: Add glamor acceleration

---

Makefile
archlinux/PKGBUILD
debian/control
debian/pulseaudio-qubes.install
pulse/75-pulseaudio-qubes.preset
pulse/pulseaudio.service.d/30_qubes.conf
pulse/start-pulseaudio-with-vchan
rpm_spec/gui-agent.spec.in

If systemd will be managing PulseAudio, then start-pulseaudio-with-vchan
should do nothing.  This requires qubes-core-agent >= 4.2.1, as older
versions disable pulseaudio.socket and pulseaudio.service.  Finally,
fix a bug in the Arch PKGBUILD.

Let systemd manage PulseAudio

---

appvm-scripts/etc/xdg-debian/xsettingsd

This saves users who create new debian template-based domUs from having to install `gnome-settings-daemon` to remove duplicate buttons.
https://forum.qubes-os.org/t/3904
QubesOS/qubes-issues#2813

Remove duplicated button from titlebar of gnome applications

---

Makefile
appvm-scripts/etc/xdgautostart/qubes-gtk4-workarounds.desktop
appvm-scripts/usr/lib/qubes/gtk4-workarounds.sh
debian/qubes-gui-agent.install
rpm_spec/gui-agent.spec.in

Apply custom CSS to workaround software rendering issues:
- black frames around popup menus
- spinner monopolizing the whole "idle loop", preventing actual work to
be done (for example in nautilus)
This is heavily based on work by @sityvb and @noskb.
The spinner disabler is done in two parts:
- animation-play-state disables actual spinning (this part frees up the
idle loop)
- opacity hides the now frozen spinner to avoid confusion (at least a
bit); it could be 'display: none', but that (at least in nautilus) is
programatically overridden
The patch is applied on user login and flag file is created to not
reapply it needlessly.
Fixes QubesOS/qubes-issues#8081
Fixes QubesOS/qubes-issues#7921
Fixes QubesOS/qubes-issues#8115

Workaround software rendering issues in GTK4

---

appvm-scripts/usrbin/qubes-run-xorg

... in GuiVM. This results in a zombie process (right now), and will
crash gui-agent when it will actually monitor its children.

Do not exit from qubes-run-xorg after starting Xorg

---

common/list.c
gui-agent/Makefile
gui-agent/vmside.c
include/list.h
xf86-input-mfndev/configure.ac
xf86-input-mfndev/src/qubes.c
xf86-qubes-common/include/xf86-qubes-common.h
xf86-video-dummy/configure.ac
xf86-video-dummy/src/Makefile.am
xf86-video-dummy/src/dummy.h
xf86-video-dummy/src/dummy_driver.c

This breaks compatibility with protocol versions older than 1.4.
Therefore, it must not be merged until this some time after GUI daemon
4.1.23 reaches stable, as 4.1.22 is buggy and older versions only
support protocols 1.3 and below.

Switch to protocol 1.4

---

appvm-scripts/etc/securitylimits.d/90-qubes-gui.conf
appvm-scripts/usr/lib/qubes/qubes-gui-agent-pre.sh
appvm-scripts/usrbin/qubes-session

The default user might not be named `user`.

Support alternate user names

---

appvm-scripts/usr/lib/qubes/qubes-keymap.sh

Avoid xkb option accumulation
https://github.com/QubesOS/qubes-issues/issues/8230
Don't add ",us" for layout "si"
https://github.com/QubesOS/qubes-gui-agent-linux/pull/139#issuecomment-1627711217

Fix two qubes-keymap.sh issues

---

gui-common/qubes-gui-runuser.c

This adds Wayland support to `qubes-gui-runuser`.  X11 support is not affected, so the same launcher (with different arguments) can be used for both Wayland and X11 sessions.

Wayland support in `qubes-gui-runuser`

---

pipewire/30_qubes.conf

This turns out to totally break Firefox's WebRTC implementation.  The clock rate and maximum quantum are deleted, while the minimum quantum is kept but commented out by default.  Users can uncomment it if they are experiencing large numbers of xruns.
With this change, I still get occasional underruns, but the audio is generally usable.  Previously it wasn't.  The underruns will be fixed by using PipeWire's delay-locked loop implementation, combined with its rate control support.
Fixes: QubesOS/qubes-issues#8415 (release blocker!)

Do not override default clock rate or quantum

---

pipewire/qubes-pw-module.c

Allow more than one buffer (to allow application / daemon preparing next
buffer when previous one is being processed). And also adjust buffer
size based on other pipewire modules.
QubesOS/qubes-issues#8415

pipewire: adjust buffer parameters

---

.gitignore
debian/control
pipewire/30_qubes.conf
pipewire/Makefile
pipewire/pw-module-run.c
pipewire/qubes-pw-module.c
rpm_spec/gui-agent.spec.in

Make the PipeWire module a driver

---

appvm-scripts/etc/securitylimits.d/90-qubes-gui.conf

This makes low-latency audio easier without having to use rtkit.

Allow Qubes group to use all realtime priorities

---

gui-agent/encoding.c

Fixes copy & paste of data containing it, such as from Windows.
Fixes: QubesOS/qubes-issues#8937

Allow carriage return in secure clipboard

---

archlinux/PKGBUILD.in
pipewire/qubes-pw-module.c

https://github.com/QubesOS/qubes-issues/issues/8975

Watch qdb entry being set and modified on start or while playing

---

appvm-scripts/etc/X11/xorg-qubes-x11vnc.conf.template
appvm-scripts/usrbin/qubes-run-x11vnc

The first fix from many...
TODO:
Fixes QubesOS/qubes-issues#9276

Fix VNC GUIVM

---

archlinux/PKGBUILD.in

qubes-set-monitor-layout relies on calling xrandr for successful operation. Make sure the archlinux template has the binary present, so the script doesn't end up running an infinite loop, utilizing CPU cycles for nothing.

Add xorg-xrandr dependence for vm-archlinux

---

appvm-scripts/etc/profile.d/qubes-gui.csh
appvm-scripts/etc/profile.d/qubes-gui.sh

Fixes: https://github.com/QubesOS/qubes-issues/issues/9268
---
Awaiting reply to https://github.com/QubesOS/qubes-issues/issues/9268#issuecomment-2175591383

Force use of software rendering

---

xf86-input-mfndev/src/labels.h
xf86-input-mfndev/src/qubes.c

Axis labels were implemented, but guarded by non-existing
HAVE_PROPERTIES+HAVE_LABELS define. Button labels were not implemented
at all (array was allocated, but not filled with any data, resulting in
a stack rubble being passed on). Fix both issues.
Fixes QubesOS/qubes-issues#9412

Fix input device labels

---

.gitlab-ci.yml
gui-agent/vmside.c

If vmside clipboard is over the maximum limit, sending one byte over maximum limit should trigger inter-vm clipboard rejection instead of truncation.
Fixes: https://github.com/QubesOS/qubes-issues/issues/9296
Fixes: https://github.com/QubesOS/qubes-issues/issues/5220

Handle oversized clipboard for GUI protocol 1.8

---

pipewire/qubes-pw-module.c

This may be more correct than using the “paused” event.

Allow hexadecimal numbers

---

rpm_spec/gui-agent.spec.in

cvt tool is split out of xorg-x11-server-Xorg in Fedora 41+, add
explicit dependency for it, as it's needed by qubes.SetMonitorLayout
service.
QubesOS/qubes-issues#9244

rpm: depend on cvt in F41+

---

gui-agent/vmside.c
xf86-input-mfndev/src/qubes.c

Better handle stopping the service while it's still starting up. And also improve handling Xorg startup errors (much simpler alternative to #176).

Improve handling early startup issues

---

Makefile
appvm-scripts/lib/systemd/user/pipewire.service.d/30_qubes.conf
debian/pipewire-qubes.install
rpm_spec/gui-agent.spec.in

If root session is started early and pipewire gets started as part of
it, it may connect to the audiovm earlier than the user's instance,
effectively stealing the connection. Upstream already has
ConditionUser=!root in relevant pulseaudio units, but not in pipewire
ones. Add similar condition to pipewire.service unit.
Fixes QubesOS/qubes-issues#9619

pipewire: prevent starting in root session

---

appvm-scripts/etc/profile.d/qubes-gui.csh
appvm-scripts/etc/profile.d/qubes-gui.sh

Also set software rendering via the new `$GDK_DISABLE` variable

---

window-icon-updater/qubes-icon-sender.desktop

Qubes icon sender allows to update applications windows icons. In practice, few windows are opened on the sys-vms. Disabling this service allows to recover some RAM without causing inconvenience.

disable qubes-icon-sender on sys-net and sys-usb

---

.gitlab-ci.yml
archlinux/PKGBUILD.in

fixes: https://github.com/QubesOS/qubes-issues/issues/9660
Reference: https://github.com/QubesOS/qubes-meta-packages/pull/75

Pull in required Pipewire dependencies for Archlinux

---

xf86-video-dummy/src/dummy.h

The function takes an argument. Actual function used there was okay, but
the field in the structure used wrong type. And GCC 15 (rightfully)
started complaining.
Use CreateWindowProcPtr type to avoid similar issue in the future.
QubesOS/qubes-issues#9807

xf86-video-dummy: fix type of CreateWindow field

---

.qubesbuilder

When formatted in double quotes, the @SOURCE_DIR@ may be problematic
with windows builder, as it will contain backslashes, and that will be
misinterpreted by the yaml parser. While the windows paths are not
relevant for those commands, .qubesbuilder file need to render correctly
in that case too.

Format commands .qubesbuilder in single quotes

---

appvm-scripts/etc/X11/xorg-qubes.conf.template

Apparently GTK considers an input device with abs axes a touchscreen,
unless it has "mouse" or "pointer" in the name. And changes behavior of
clicks to make it more "touch friendly". Rename the device to make GTK
apps happy.
Fixes QubesOS/qubes-issues#7316

Include 'pointer' in the qubes input device name

---

pipewire/qubes-pw-module.c

This cause stream to never be paused in practice...
This reverts commit fc04d11888ed704de4888fc95357c1161c36cea7.

Revert "Use the drained callback on the playback stream"

---

gui-agent/Makefile
gui-agent/video-ext-client.c
gui-agent/video-ext-client.h
gui-agent/vmside.c
include/qubes-video-ext.h
include/unix-addr.h
xf86-input-mfndev/src/qubes.c
xf86-video-dummy/src/dummy_driver.c

We rely on composite redirect mode of the X server to get per window pixmaps. Those are setup/teared-down in compRealizeWindow/ compUnrealizeWindow (via compCheckRedirect).
So not realized windows don't have a per window pixmap. Sending grant refs for them was always broken since we didn't send the offset into the screen pixmap in those cases. But with the recent change to not allocate grant refs for the screen pixmap this leads to a noticable error message.
So don't try to send grant refs for not realized windows. This means that the configure before mapping will not contiain grant refs. But when we map the window we will get a damage event because of the new pixmap compRealizeWindow has allocated and send them then. So this should be fine.

Don't try to send grants for not realized windows

---

gui-agent/vmside.c
xf86-video-dummy/src/dummy_driver.c

Fix two small codestyle issues I didn't notice in #236 and #239 before merge.

Small follow up to #236 and #239

---

gui-agent/vmside.c

This seems to have been the original intent (see [qubes-gui-daemon#d19a4a7](/QubesOS/qubes-gui-daemon/commit/d19a4a76c4c667ad9ad62b848accd28ba8538cac)), but as far as I can tell the VM side was never implemented.
I've only compared quickly, but it makes a huge difference because of the lack of GPU acceleration for VMs.

Fixed ignored X property NET_WM_STATE_HIDDEN

---

appvm-scripts/usr/lib/qubes/qubes-gui-agent-pre.sh

For qubes that are using an in-qube kernel, the nomodeset argument is not necessarily passed to the kernel command line, so we should unbind Xen's VGA adapter from bochs-drm, if bound, to prevent performance issues.
This fixes https://github.com/QubesOS/qubes-issues/issues/10105.

Unbind Xen VGA adapter from bochs-drm on boot

---

appvm-scripts/usr/lib/qubes/qubes-gui-agent-pre.sh

It isn't installed in some templates by default. Fortunately, it's quite
easy to find the device by simply exploring sysfs.

Avoid using lspci in qubes-gui-agent-pre.sh
